/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannersHouseRouteImport } from './routes/planners.house'
import { Route as PlannersInflationRouteImport } from './routes/planners.inflation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannersHouseRoute = PlannersHouseRouteImport.update({
  id: '/planners/house',
  path: '/planners/house',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannersInflationRoute = PlannersInflationRouteImport.update({
  id: '/planners/inflation',
  path: '/planners/inflation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/expenses': typeof ExpensesRoute
  '/goals': typeof GoalsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/planners/house': typeof PlannersHouseRoute
  '/planners/inflation': typeof PlannersInflationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/expenses': typeof ExpensesRoute
  '/goals': typeof GoalsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/planners/house': typeof PlannersHouseRoute
  '/planners/inflation': typeof PlannersInflationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/expenses': typeof ExpensesRoute
  '/goals': typeof GoalsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/planners/house': typeof PlannersHouseRoute
  '/planners/inflation': typeof PlannersInflationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/expenses'
    | '/goals'
    | '/login'
    | '/profile'
    | '/planners/house'
    | '/planners/inflation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/expenses'
    | '/goals'
    | '/login'
    | '/profile'
    | '/planners/house'
    | '/planners/inflation'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/expenses'
    | '/goals'
    | '/login'
    | '/profile'
    | '/planners/house'
    | '/planners/inflation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  ExpensesRoute: typeof ExpensesRoute
  GoalsRoute: typeof GoalsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  PlannersHouseRoute: typeof PlannersHouseRoute
  PlannersInflationRoute: typeof PlannersInflationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planners/house': {
      id: '/planners/house'
      path: '/planners/house'
      fullPath: '/planners/house'
      preLoaderRoute: typeof PlannersHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planners/inflation': {
      id: '/planners/inflation'
      path: '/planners/inflation'
      fullPath: '/planners/inflation'
      preLoaderRoute: typeof PlannersInflationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  ExpensesRoute: ExpensesRoute,
  GoalsRoute: GoalsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  PlannersHouseRoute: PlannersHouseRoute,
  PlannersInflationRoute: PlannersInflationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
